# Generated by Django 4.1.7 on 2023-04-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChessChannelsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='moves',
            field=models.TextField(blank=True),
        ),
    ]
