# Generated by Django 4.1.7 on 2023-04-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChessChannelsApp', '0002_game_moves'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='fens',
            field=models.TextField(blank=True),
        ),
    ]
