# Generated by Django 4.1.7 on 2023-04-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChessChannelsApp', '0003_game_fens'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='black_full_time',
            field=models.IntegerField(blank=True, default=100000),
        ),
        migrations.AddField(
            model_name='game',
            name='white_full_time',
            field=models.IntegerField(blank=True, default=100000),
        ),
    ]
