# Generated by Django 4.1.7 on 2023-04-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChessChannelsApp', '0004_game_black_full_time_game_white_full_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_mode',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
