# Generated by Django 4.1.7 on 2023-04-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChessChannelsApp', '0005_game_game_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='increment',
            field=models.IntegerField(default=0),
        ),
    ]
