# Generated by Django 4.1.7 on 2023-04-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChessChannelsApp', '0009_puzzle_board_orientation'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='users',
            field=models.TextField(blank=True),
        ),
    ]
